### ISSUE TITLE
DataTable sorted column arrow direction wrong

### ISSUE THREAD

**Issue by rikkertbf** [IBM/carbon-components-react#1111]
In exploring use of DataTable component in our app, noticed that the sort order indication in the table header appears to be _counter-intuitive_ (and inconsistent with most other grid impls - including our existing table component). 
I.E. up arrow represents DESC (as well as unordered state), and down arrow for ASC...
Confirmed per #carbon-react channel discussion.

Found in sample provided here: 
https://pages.github.ibm.com/cloud-integration-design/ap-carbon-theme/?selectedKind=DataTable&selectedStory=with%20sorting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

![image](https://user-images.githubusercontent.com/18743489/42980593-03fce60c-8ba6-11e8-81ac-373ab139e8fe.png)

**Comment by lovemecomputer** [comment]
addressed in https://github.com/IBM/carbon-components-react/pull/1234

@rikkertbf  thanks so much for noticing this! it's a small subtle thing, i think it was just temping to type "caret down" for descending order, but your right, it should be "caret up", at least to match with the mac programs i'm looking at!

**Comment by Bluedrop** [comment]
I think this should be configurable instead of fixed one way or another. I've encountered libraries and tools that use it differently, as well as client demanding the arrows to be pointing a certain way. Granted you can program each column sort as needed, but if you need all tables in the entire app to just show it "backwards" it would be so much easier to just configure what icon to use....

There is logic in both sorting orders: iconCaretUp has a **small** top and **big** bottom (suggesting the ascending order) and iconCareDown has a **big** top and a **small** bottom. Granted not so significant on strings, but if we're talking about **big** and **small** numbers the suggested sorting is different.

Just a thought :) I may fork this and add a configurable icon if that's permitted :)
