### ISSUE TITLE
Warning in browser console when using the Modal component

### ISSUE THREAD

**Issue by jrpomeroy** [IBM/carbon-components-react#1180]
## Detailed description

> Describe in detail the issue you're having.

I've upgraded to the latest version (9.7.0) and when I load any page that has a Modal on it I see this warning in the browser console:

![image](https://user-images.githubusercontent.com/18622709/43980413-a2b175e2-9cb3-11e8-89f4-54faf6eb3a9a.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

Latest Chrome

> What version of the Carbon Design System are you using?

carbon-components-react 9.7.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Not a major issue, just an annoyance

## Steps to reproduce the issue

1. Add a Modal somewhere in your code
2. Run your dev server
3. Navigate to the page with the Modal on it
4. See warning in browser console

**Comment by asudoh** [comment]
@emyarod My apologies for not catching this, but would you be interested in fixing this? I believe this is as simple as adding `selectorPrimaryFocus` to [here](https://github.com/emyarod/carbon-components-react/blob/5dc69b9/src/components/Modal/Modal.js#L164). Let me know otherwise, which will be no problem - Thanks!
