### ISSUE TITLE
Unexpected blank div at bottom of page when using Date Picker Calendar

### ISSUE THREAD

**Issue by jpcrisos** [IBM/carbon-components-react#1279]
## Detailed description

> Describe in detail the issue you're having.

The DatePicker adds an invisible div at the bottom of the body that contributes to the page flow. It can cause unexpected page shifting if using `scrollIntoView()`

> Is this issue related to a specific component?

DatePicker, DatePickerInput

> What did you expect to happen? What happened instead? What would you like to see changed?

The animation container used for the calendar shouldn't influence the page flow if it's closed/invisible.

> What browser are you working in?

Chrome, IE11

> What version of the Carbon Design System are you using?

9.11.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

Please refer to code sample. The div is set to 100vh, but there's still a vertical scrollbar. Adding `display: none;` to the date picker calendar css appears to fix the issue.

> Please create a reduced test case in code sandbox
https://codesandbox.io/s/zqko55mm53

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Flatpickr, our date picker is based on, uses `visibility:hidden` instead of `display:none` to hide non-open calendar dropdown. The CSS class is `flatpickr-calendar`. Feel free to change the style if it achieves what you want.

BTW could you articulate what the issue with vertical scroll bar and `scrollIntoView()`? I couldn't see any issue running https://codesandbox.io/s/zqko55mm53. Thanks!

**Comment by jpcrisos** [comment]
I suppose the issue is more on the Flatpickr side. For the sandbox, the issue was that the scrollbar is being shown when no content is there to scroll to.

**Comment by joshblack** [comment]
Sounds good, @jpcrisos! Going to close this for now, unless I misunderstood and then feel free to comment and I can re-open! 👍
