### ISSUE TITLE
Update invalid number input

### ISSUE THREAD

**Issue by alisonjoseph** [IBM/carbon-components-react#1506]
Need to add in html updates from vanilla library to React

https://github.com/IBM/carbon-components/pull/1360

**Comment by vividh** [comment]
I'll take this!

**Comment by asudoh** [comment]
Great - Thanks @vividh! Please make sure the HTML change is roped off via [`componentsX` named export from `FeatureFlags.js`](https://github.com/IBM/carbon-components-react/blob/v6.40.0/src/internal/FeatureFlags.js#L13). More details can be found at https://github.com/IBM/carbon-components-react/tree/v6.40.0/src/internal#example-rendering-foo-if-afeatureflag-is-true-render-bar-otherwise. Don't hesitate to ping me if you have any questions. Thanks!

**Comment by asudoh** [comment]
^ Oops please disregard above message, my apologies - I was referring to another issue requiring markup change and this change doesn't have to be roped off.
