### ISSUE TITLE
[Loading] The end animation is not working in IE and Edge.

### ISSUE THREAD

**Issue by miniwangdali** [IBM/carbon-components-react#1655]
## Detailed description
![image](https://user-images.githubusercontent.com/5415452/49963306-8e1c8600-fee5-11e8-926f-d69ce037ecb5.png)
The circle should not display after the animation ends. But it is still there. So I guess the animation doesn't run perfectly on IE and Edge.

> What browser are you working in?
IE/Edge

> What version of the Carbon Design System are you using?
6.44.0

## Steps to reproduce the issue
Simply try `Loading` component in IE 11/Edge.
CodeSandbox does not work in IE 🤦‍♂️

**Comment by asudoh** [comment]
Hi :wave: I see end animation works with IE at http://react.carbondesignsystem.com/?selectedKind=Loading&selectedStory=Default - You can go to KNOBS tab at the bottom and check/uncheck `active` prop to see that. IIUC @emyarod saw that end animation works with Edge, too. One thing to note is that the loading spinner has to be kept visible (not hidden) even after the spinner gets deactivated, in order to see the end animation. Feel free to let us know if it's not the case for you!
