### ISSUE TITLE
TileGroup: can't use flexbox on Chrome due to fieldset

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-components-react#1999]
### Summary

Since TileGroup renders a fieldset it is not possible to use flexbox to change the TileGroup to render the tiles horizontally or in a grid on Chrome.  See this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=375693

### Justification

More flexibility in how we use the TileGroup component from a UX perspective.
Check out this codesandbox in Chrome and Firefox, Firefox shows the desired behavior.
https://codesandbox.io/s/nk30xz0p3m

**Comment by emyarod** [comment]
hi @scottdickerson thanks for reporting this! I believe we have run into this issue in #1114, where avoiding `<fieldset>` will throw [a11y errors](https://aat.mybluemix.net/token/97b22e9c-25bd-48ea-be04-c77a42c72b11/a313b75d-5599-420e-9695-15c1599da92a/doc/w3/help/en-US/idhi_accessibility_check_g1029.html). The inconsistent flexbox support is due to browser implementation differences as you've found, and I think we will do a bit more research to figure out a workaround that we can apply across all browserrs

**Comment by GodAImighty** [comment]
If you want horizontal fieldset things, use `inline-block`

**Comment by scottdickerson** [comment]
cool thanks, will close.
