### ISSUE TITLE
Dropdown V1/V2: Currently selected option appearing in dropdown

### ISSUE THREAD

**Issue by JordanWSmith15** [IBM/carbon-components-react#2006]
Small discrepancy between base Carbon and React.

In the base Carbon example, currently selected option is not visible:
https://www.carbondesignsystem.com/components/dropdown/code
![Carbon](https://user-images.githubusercontent.com/21066152/54226611-93817080-44d4-11e9-8b9e-693105f29c75.png)

In the React storybook, curretly selected option is still visible:
![Screen Shot 2019-03-12 at 2 37 50 PM](https://user-images.githubusercontent.com/21066152/54226755-d3485800-44d4-11e9-862b-4bdfd3abde71.png)

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! If you go to http://react.carbondesignsystem.com/?selectedKind=Dropdown&selectedStory=default, you'll find the selected dropdown item has a highlight, which is new in `v10` - We use that style rather than hiding the selected item like we did in `v9`. Hope it clarifies things!
