### ISSUE TITLE
Match dropdown to experimental spec

### ISSUE THREAD

**Issue by emyarod** [IBM/carbon-components-react#2022]
Related:

https://github.com/IBM/carbon-components/issues/1955

https://github.com/IBM/carbon-components/issues/1648

https://github.com/IBM/carbon-components/pull/1994

Depends on https://github.com/IBM/carbon-components/pull/2181

**Comment by laurenmrice** [comment]
*Changes:*

- [ ] If the dropdown is scrollable could we show the drawer with the fourth option text cut off? I feel like this will better show that the dropdown is actually scrollable instead of showing an end rule after Option 3.
<img width="414" alt="Screen Shot 2019-03-19 at 1 36 28 PM" src="https://user-images.githubusercontent.com/43969356/54632534-51b07700-4a4c-11e9-8b08-b9ce6779d6f3.png">

- [ ] The top dropdown label is getting a hover color when selecting other options. Should not be getting hover.
<img width="350" alt="Screen Shot 2019-03-19 at 1 36 45 PM" src="https://user-images.githubusercontent.com/43969356/54632621-87edf680-4a4c-11e9-9956-ac6792f12eab.png">

- [ ] Options in drawer all still in Helvetica typeface. Needs to be Plex.
![Screen Shot 2019-03-19 at 1 42 04 PM](https://user-images.githubusercontent.com/43969356/54632773-d602fa00-4a4c-11e9-9f14-c23a1e3936a3.png)

- [ ] After selecting an option, the drawer closes but the bottom rule color should change back to ui-04 (#8C8C8C). Once you click onto the actual page it does change color again, but it should change right after the drawer is closed.
![Screen Shot 2019-03-19 at 1 44 03 PM](https://user-images.githubusercontent.com/43969356/54632936-1f534980-4a4d-11e9-8edb-59f904f1bf86.png)

- [ ] In Safari I am getting some weird glitches in the drawer. 
<img width="425" alt="Screen Shot 2019-03-19 at 1 45 46 PM" src="https://user-images.githubusercontent.com/43969356/54633079-6b9e8980-4a4d-11e9-82e1-d22e3692744a.png">

- [ ] The focus needs to cover the bottom rule. Right now it is showing on top.
<img width="1054" alt="Screen Shot 2019-03-19 at 1 46 51 PM" src="https://user-images.githubusercontent.com/43969356/54633142-9092fc80-4a4d-11e9-8a2b-59cee3667a38.png">
