### ISSUE TITLE
How to build a responsive UI with carbon-components-react?

### ISSUE THREAD

**Issue by harikrishnanp** [IBM/carbon-components-react#2270]
## Summary
How to build a responsive UI with carbon-components-react?

## Relevant information

Are you providing any guidelines for building a responsive UI with carbon-components-react?

**Comment by asudoh** [comment]
Hi :wave: if you search for `breakpoint` keyword in `carbon-components` source code, you'll see how we provide responsive UI - For example, the tabs UI changes to the dropdown UI when the browser viewport is not wide enough. That said, responsive UI thing tends to be about our style library (`carbon-components`) rather than the React variant (here). Hope it clarifies things!
