### ISSUE TITLE
Request: If possible, change ModalWrapper base element to a span

### ISSUE THREAD

**Issue by ColbyJohnIBM** [IBM/carbon-components-react#642]
## Detailed description

> Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

When using the ModalWrapper, the use of a `div` as the base element forces the trigger button to have `display: block` styling. Therefore, it requires additional CSS and/or wrappers around the ModalWrapper to keep it inline. While this is generally fairly easy for developers to do, it feels like the component itself should not force block behavior in the first place.

[Line of code in question](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ModalWrapper/ModalWrapper.js#L91)

> Is this issue related to a specific component?

Yes, ModalWrapper

**Comment by joshblack** [comment]
Hi @ColbyJohnIBM! 👋  Thanks so much for taking the time to make this issue 😄

This definitely seems like a fair feature request. Since we're creating this as sugar on top of the existing elements, we're not really bound by the system here but instead are trying to support the best developer experience using the Modal components.

How do the rest of carbon devs feel about this feature request? cc @carbon-design-system/ui

**Comment by alisonjoseph** [comment]
I agree this seems like a fair request, however, my concern would be if we update this then we would break the layout for someone who expects it to render as a block element.

**Comment by ColbyJohnIBM** [comment]
That's a good point-- I can appreciate the desire not to break things. And again, it's easy enough for developers to fix. It was just a small pain point for our use case, so I wanted to make your team aware of it. Whichever direction you all decide to go in, I appreciate the quick response.

**Comment by tw15egan** [comment]
Maybe we should tag this as something we can address for the v9 release?
